apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: testphp7
      app.kubernetes.io/component: testphp
      app.kubernetes.io/instance: testphp
    name: testphp7
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: testphp7
      app.kubernetes.io/component: testphp7
      app.kubernetes.io/instance: testphp7
    name: testphp7
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: testphp7:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/azygmunciak/testphp.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.3
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: KJGiMFdo-EMOnpD_5cnZ
      type: GitHub
    - generic:
        secret: XA1N8ivqOJtvSGtUjOV3
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: testphp7
      app.kubernetes.io/component: testphp7
      app.kubernetes.io/instance: testphp7
    name: testphp7
  spec:
    replicas: 1
    selector:
      deploymentconfig: testphp7
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: testphp7
      spec:
        containers:
        - image: testphp7:latest
          name: testphp7
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - testphp7
        from:
          kind: ImageStreamTag
          name: testphp7:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: testphp7
      app.kubernetes.io/component: testphp7
      app.kubernetes.io/instance: testphp7
    name: testphp7
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: testphp7
  status:
    loadBalancer: {}
kind: List
metadata: {}
