apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: testphp7
  name: testphp7
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: testphp7
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: testphp7
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/testphp7/testphp7:latest
        name: testphp7
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
  test: false
